# Configuration file for ts-backend-check validation.
# See https://github.com/activist-org/ts-backend-check for details.

auth:
  backend_model_path: src/ts_backend_check/test_project/backend/models.py
  ts_interface_paths:
  - src/ts_backend_check/test_project/frontend/valid_interfaces_2.ts
  - src/ts_backend_check/test_project/frontend/valid_interfaces_1.ts
  check_blank_model_fields: false
  backend_models_to_ignore: null
